# Generated by Django 3.1.7 on 2021-05-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedbackapp', '0002_feedback_oncourse_feedback_onfaculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_oncourse',
            name='number',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='feedback_onfaculty',
            name='number',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
