# Generated by Django 3.0.5 on 2021-05-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='facultyfeedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('adequacy_of_ourse_sylabus', models.CharField(max_length=10)),
                ('Background_for_benefiting_courcr', models.CharField(max_length=10)),
                ('course_difficulty_to_understand', models.CharField(max_length=10)),
                ('syllabus_completeing_range', models.CharField(max_length=10)),
                ('library_material_availability', models.CharField(max_length=10)),
                ('difficulty_to_get_material', models.CharField(max_length=10)),
                ('levelof_preparation_for_class', models.CharField(max_length=10)),
                ('how_teacher_able_to_communicate', models.CharField(max_length=10)),
                ('how_teacher_encourages_student', models.CharField(max_length=10)),
                ('method_of_encouraging', models.CharField(max_length=10)),
                ('how_helps_advicing', models.CharField(max_length=10)),
                ('teachers_approach', models.CharField(max_length=10)),
                ('Internal_assessment', models.CharField(max_length=10)),
                ('effect_of_internal_assesment', models.CharField(max_length=10)),
                ('how_often_gets_feedback_on_performance', models.CharField(max_length=10)),
                ('Were_your_assignments_discussed_with_you', models.CharField(max_length=10)),
                ('Were_you_provided_with_course_contributory_lecture_too_at_the_beginning', models.CharField(max_length=10)),
            ],
        ),
    ]
